export enum AdminMenu {
  USER_MANAGEMENT = "USER_MANAGEMENT",
  JOB = "JOB",
  ORGANIZATION = "ORGANIZATION",
  QUALIFICATIONS = "QUALIFICATIONS",
  NATIONALITIES = "NATIONALITIES",
  CORPORATE_BRANDING = "CORPORATE_BRANDING",
  CONFIGURATION = "CONFIGURATION",
}